<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMPBuQF0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMPBuQF0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMPBuQF0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMPBuQF0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMPBuQF0\App_KernelDevDebugContainer([
    'container.build_hash' => 'MPBuQF0',
    'container.build_id' => '87d6752e',
    'container.build_time' => 1700951132,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMPBuQF0');
