<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOFWba7C\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOFWba7C/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOFWba7C.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOFWba7C\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOFWba7C\App_KernelDevDebugContainer([
    'container.build_hash' => 'OFWba7C',
    'container.build_id' => '343e6028',
    'container.build_time' => 1700920392,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOFWba7C');
