<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8DRgrSr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8DRgrSr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8DRgrSr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8DRgrSr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8DRgrSr\App_KernelDevDebugContainer([
    'container.build_hash' => '8DRgrSr',
    'container.build_id' => 'd8a0903c',
    'container.build_time' => 1700929842,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8DRgrSr');
