<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'Symfony.Component.Form.Form' => 0,
'IteratorAggregate' => 1,
'Symfony.Component.Form.FormInterface' => 2,
'Symfony.Component.Form.ClearableErrorsInterface' => 3,
'Traversable' => 4,
'Countable' => 5,
'ArrayAccess' => 6,
'App.Entity.City' => 7,
'App.Entity.Forecast' => 8,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Form\\Extension\\Validator\\Constraints\\Form'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Form\\Extension\\Validator\\Constraints\\Form')),
        ],
        null,
        [
            'stdClass' => [
                'constraints' => [
                    [
                        $o[1],
                    ],
                ],
                'constraintsByGroup' => [
                    [
                        'Default' => [
                            $o[1],
                        ],
                        'Form' => [
                            $o[1],
                        ],
                    ],
                ],
                'traversalStrategy' => [
                    2,
                ],
                'name' => [
                    'Symfony\\Component\\Form\\Form',
                ],
                'defaultGroup' => [
                    'Form',
                ],
                'groups' => [
                    1 => [
                        'Default',
                        'Form',
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'IteratorAggregate',
                ],
                'defaultGroup' => [
                    'IteratorAggregate',
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Symfony\\Component\\Form\\FormInterface',
                ],
                'defaultGroup' => [
                    'FormInterface',
                ],
            ],
        ],
        $o[0],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Symfony\\Component\\Form\\ClearableErrorsInterface',
                ],
                'defaultGroup' => [
                    'ClearableErrorsInterface',
                ],
            ],
        ],
        $o[0],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Traversable',
                ],
                'defaultGroup' => [
                    'Traversable',
                ],
            ],
        ],
        $o[0],
        []
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Countable',
                ],
                'defaultGroup' => [
                    'Countable',
                ],
            ],
        ],
        $o[0],
        []
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'ArrayAccess',
                ],
                'defaultGroup' => [
                    'ArrayAccess',
                ],
            ],
        ],
        $o[0],
        []
    );
},
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (($f = &\Symfony\Component\VarExporter\Internal\Registry::$factories)['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
            ($f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'))(),
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Validator\\Constraints\\NotBlank'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\NotBlank')),
            $f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'](),
            clone $p['Symfony\\Component\\Validator\\Constraints\\NotBlank'],
            clone ($p['Symfony\\Component\\Validator\\Constraints\\Length'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\Length')),
            $f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'](),
            clone $p['Symfony\\Component\\Validator\\Constraints\\NotBlank'],
            clone ($p['Symfony\\Component\\Validator\\Constraints\\Range'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\Range')),
            $f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'](),
            clone $p['Symfony\\Component\\Validator\\Constraints\\NotBlank'],
            clone $p['Symfony\\Component\\Validator\\Constraints\\Range'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\City',
                    'name',
                    3 => 'countryCode',
                    6 => 'latitude',
                    9 => 'longitude',
                ],
                'defaultGroup' => [
                    'City',
                ],
                'members' => [
                    [
                        'name' => [
                            $o[1],
                        ],
                        'countryCode' => [
                            $o[3],
                        ],
                        'latitude' => [
                            $o[6],
                        ],
                        'longitude' => [
                            $o[9],
                        ],
                    ],
                ],
                'properties' => [
                    [
                        'name' => $o[1],
                        'countryCode' => $o[3],
                        'latitude' => $o[6],
                        'longitude' => $o[9],
                    ],
                ],
                'constraints' => [
                    1 => [
                        $o[2],
                    ],
                    3 => [
                        $o[4],
                        $o[5],
                    ],
                    6 => [
                        $o[7],
                        $o[8],
                    ],
                    9 => [
                        $o[10],
                        $o[11],
                    ],
                ],
                'constraintsByGroup' => [
                    1 => [
                        'create' => [
                            $o[2],
                        ],
                        'edit' => [
                            $o[2],
                        ],
                    ],
                    3 => [
                        'create' => [
                            $o[4],
                            $o[5],
                        ],
                        'edit' => [
                            $o[4],
                            $o[5],
                        ],
                    ],
                    6 => [
                        'create' => [
                            $o[7],
                            $o[8],
                        ],
                        'edit' => [
                            $o[7],
                            $o[8],
                        ],
                    ],
                    9 => [
                        'create' => [
                            $o[10],
                            $o[11],
                        ],
                        'edit' => [
                            $o[10],
                            $o[11],
                        ],
                    ],
                ],
                'class' => [
                    1 => 'App\\Entity\\City',
                    3 => 'App\\Entity\\City',
                    6 => 'App\\Entity\\City',
                    9 => 'App\\Entity\\City',
                ],
                'property' => [
                    1 => 'name',
                    3 => 'countryCode',
                    6 => 'latitude',
                    9 => 'longitude',
                ],
                'groups' => [
                    2 => [
                        'create',
                        'edit',
                    ],
                    4 => [
                        'create',
                        'edit',
                    ],
                    [
                        'create',
                        'edit',
                    ],
                    7 => [
                        'create',
                        'edit',
                    ],
                    [
                        'create',
                        'edit',
                    ],
                    10 => [
                        'create',
                        'edit',
                    ],
                    [
                        'create',
                        'edit',
                    ],
                ],
                'max' => [
                    5 => 2,
                    8 => 90,
                    11 => 180,
                ],
                'min' => [
                    5 => 2,
                    8 => -90,
                    11 => -180,
                ],
            ],
        ],
        $o[0],
        []
    );
},
8 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (($f = &\Symfony\Component\VarExporter\Internal\Registry::$factories)['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
            ($f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'))(),
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Validator\\Constraints\\NotBlank'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\NotBlank')),
            $f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'](),
            clone $p['Symfony\\Component\\Validator\\Constraints\\NotBlank'],
            clone ($p['Symfony\\Component\\Validator\\Constraints\\Range'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\Range')),
            $f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'](),
            clone $p['Symfony\\Component\\Validator\\Constraints\\NotBlank'],
            clone $p['Symfony\\Component\\Validator\\Constraints\\Range'],
            $f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'](),
            clone $p['Symfony\\Component\\Validator\\Constraints\\NotBlank'],
            clone $p['Symfony\\Component\\Validator\\Constraints\\Range'],
            $f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'](),
            clone $p['Symfony\\Component\\Validator\\Constraints\\NotBlank'],
            clone $p['Symfony\\Component\\Validator\\Constraints\\Range'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'App\\Entity\\Forecast',
                    'date',
                    3 => 'celsius',
                    6 => 'wind',
                    9 => 'pressure',
                    12 => 'rain',
                ],
                'defaultGroup' => [
                    'Forecast',
                ],
                'members' => [
                    [
                        'date' => [
                            $o[1],
                        ],
                        'celsius' => [
                            $o[3],
                        ],
                        'wind' => [
                            $o[6],
                        ],
                        'pressure' => [
                            $o[9],
                        ],
                        'rain' => [
                            $o[12],
                        ],
                    ],
                ],
                'properties' => [
                    [
                        'date' => $o[1],
                        'celsius' => $o[3],
                        'wind' => $o[6],
                        'pressure' => $o[9],
                        'rain' => $o[12],
                    ],
                ],
                'constraints' => [
                    1 => [
                        $o[2],
                    ],
                    3 => [
                        $o[4],
                        $o[5],
                    ],
                    6 => [
                        $o[7],
                        $o[8],
                    ],
                    9 => [
                        $o[10],
                        $o[11],
                    ],
                    12 => [
                        $o[13],
                        $o[14],
                    ],
                ],
                'constraintsByGroup' => [
                    1 => [
                        'create' => [
                            $o[2],
                        ],
                        'edit' => [
                            $o[2],
                        ],
                    ],
                    3 => [
                        'create' => [
                            $o[4],
                            $o[5],
                        ],
                        'edit' => [
                            $o[4],
                            $o[5],
                        ],
                    ],
                    6 => [
                        'create' => [
                            $o[7],
                            $o[8],
                        ],
                        'edit' => [
                            $o[7],
                            $o[8],
                        ],
                    ],
                    9 => [
                        'create' => [
                            $o[10],
                            $o[11],
                        ],
                        'edit' => [
                            $o[10],
                            $o[11],
                        ],
                    ],
                    12 => [
                        'create' => [
                            $o[13],
                            $o[14],
                        ],
                        'edit' => [
                            $o[13],
                            $o[14],
                        ],
                    ],
                ],
                'class' => [
                    1 => 'App\\Entity\\Forecast',
                    3 => 'App\\Entity\\Forecast',
                    6 => 'App\\Entity\\Forecast',
                    9 => 'App\\Entity\\Forecast',
                    12 => 'App\\Entity\\Forecast',
                ],
                'property' => [
                    1 => 'date',
                    3 => 'celsius',
                    6 => 'wind',
                    9 => 'pressure',
                    12 => 'rain',
                ],
                'groups' => [
                    2 => [
                        'create',
                        'edit',
                    ],
                    4 => [
                        'create',
                        'edit',
                    ],
                    [
                        'create',
                        'edit',
                    ],
                    7 => [
                        'create',
                        'edit',
                    ],
                    [
                        'create',
                        'edit',
                    ],
                    10 => [
                        'create',
                        'edit',
                    ],
                    [
                        'create',
                        'edit',
                    ],
                    13 => [
                        'create',
                        'edit',
                    ],
                    [
                        'create',
                        'edit',
                    ],
                ],
                'min' => [
                    5 => -50,
                    8 => 0,
                    11 => 850,
                    14 => 0,
                ],
                'max' => [
                    5 => 60,
                    8 => 200,
                    11 => 1100,
                    14 => 100,
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
