<?php

namespace ContainerMPBuQF0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ushg3HtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ushg3Ht' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ushg3Ht'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'util' => ['privates', 'App\\Service\\WeatherUtil', 'getWeatherUtilService', true],
        ], [
            'util' => 'App\\Service\\WeatherUtil',
        ]);
    }
}
